# GitHub Actions

# needs: одижает завершения джоба в скобках
# глобальные переменный задаюся после name ввеху
# | pipe

name: CI_CD
env:
   APLICATION_NAME: "Test"
   DEPLOY_PACKAGE_NAME   : "test-deploy-ver-${{ github.sha }}"

on:
  push:
     branches: 
        - master
        
        
jobs:
  my_testing:
     runs-on: ubuntu-latest
     
     steps: 
     - name: Print Hello Message in Testing
       run : echo "Hello world from testing"
       
       
     - name: Execute few commands
       run : |
           echo "Hello message 1"
           echo "Hello message 2"
           echo "Application name:${{ env.APPLICATION_NAME }}"
     
  my_deploy:
     runs-on: ubuntu-latest
     needs: [my_testing]
     
     steps: 
     - name: Print Hello Message in Deploy
       run : echo "Hello world from deploy"  
       
     - name: Print Deploy package
       run : echo "Deploy package:${{ env.DEPLOY_PACKAGE_NAME }}"
     
